// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.ContextClasses;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240604130911_mtn2")]
    partial class mtn2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "4085410a-1f78-48b6-b0ba-fc789807dd63",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5704),
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "297e3c66-2a69-4a33-bed0-68e8f70c7996",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(6054),
                            Email = "metinmustafaaltintas@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "METINMUSTAFAALTINTAS@GMAIL.COM",
                            NormalizedUserName = "METIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEB9PuNMcbgBuluwMZXCFRhe2HjczgCyZGTd15cht3eoZRN+6mGPSLha/NOS8K43N3A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "50e5fe7c-bfb2-40d1-af1a-9a61961087a4",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "metin"
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserProfile", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 760, DateTimeKind.Local).AddTicks(9228),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Health",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(2717),
                            Description = "Dolore iusto quam voluptas alias sinema ducimus koyun bahar ekşili.",
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Outdoors",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(3130),
                            Description = "Et dolores koştum gül sıfat incidunt voluptatum sit çobanın mi.",
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Computers",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(3234),
                            Description = "Aspernatur aliquam vel et doloremque voluptatum lambadaki bundan nihil değerli.",
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Clothing",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(3317),
                            Description = "Olduğu numquam sunt ut şafak gül veniam velit dolayı camisi.",
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Kids",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(3394),
                            Description = "Adresini sit layıkıyla yaptı için sıla kapının sarmal ullam aperiam.",
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Shoes",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(3472),
                            Description = "İnventore eos aliquam doğru minima minima ötekinden mi ut consequatur.",
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Kids",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(3551),
                            Description = "İncidunt ona ipsa layıkıyla laudantium sayfası ducimus telefonu balıkhaneye autem.",
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Movies",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(3622),
                            Description = "Consequatur ipsa domates ut duyulmamış fugit illo balıkhaneye koştum çünkü.",
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Sports",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(3692),
                            Description = "Patlıcan olduğu çıktılar sarmal eaque ratione oldular non corporis adipisci.",
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Movies",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(3767),
                            Description = "Makinesi illo bilgiyasayarı consequuntur magnam camisi adanaya umut tempora ve.",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceOfOrder")
                        .HasColumnType("money");

                    b.Property<int?>("ShipperID")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AppUserID");

                    b.HasIndex("ShipperID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(3927),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Licensed Soft Mouse",
                            Status = 1,
                            UnitPrice = 458.92m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(4195),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Unbranded Rubber Gloves",
                            Status = 1,
                            UnitPrice = 579.75m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(4301),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Small Soft Keyboard",
                            Status = 1,
                            UnitPrice = 466.59m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(4397),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Ergonomic Granite Bacon",
                            Status = 1,
                            UnitPrice = 760.41m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(4493),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Refined Soft Car",
                            Status = 1,
                            UnitPrice = 20.96m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 6,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(4599),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Rustic Cotton Shirt",
                            Status = 1,
                            UnitPrice = 877.87m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 7,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(4695),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Ergonomic Wooden Chips",
                            Status = 1,
                            UnitPrice = 535.90m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 8,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(4789),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Awesome Wooden Chicken",
                            Status = 1,
                            UnitPrice = 994.45m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 9,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(4883),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Gorgeous Cotton Computer",
                            Status = 1,
                            UnitPrice = 576.32m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 10,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(4988),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Refined Metal Mouse",
                            Status = 1,
                            UnitPrice = 964.62m,
                            UnitsInStock = 100
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.ProductAndProductAttribute", b =>
                {
                    b.Property<int>("ProductAttributeID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductAttributeID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductAndProductAttributes");

                    b.HasData(
                        new
                        {
                            ProductAttributeID = 1,
                            ProductID = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5429),
                            Status = 1,
                            Value = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            ProductAttributeID = 2,
                            ProductID = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5465),
                            Status = 1,
                            Value = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            ProductAttributeID = 3,
                            ProductID = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5487),
                            Status = 1,
                            Value = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            ProductAttributeID = 4,
                            ProductID = 4,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5510),
                            Status = 1,
                            Value = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            ProductAttributeID = 5,
                            ProductID = 5,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5532),
                            Status = 1,
                            Value = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart"
                        },
                        new
                        {
                            ProductAttributeID = 6,
                            ProductID = 6,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5556),
                            Status = 1,
                            Value = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J"
                        },
                        new
                        {
                            ProductAttributeID = 7,
                            ProductID = 7,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5578),
                            Status = 1,
                            Value = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            ProductAttributeID = 8,
                            ProductID = 8,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5600),
                            Status = 1,
                            Value = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            ProductAttributeID = 9,
                            ProductID = 9,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5621),
                            Status = 1,
                            Value = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart"
                        },
                        new
                        {
                            ProductAttributeID = 10,
                            ProductID = 10,
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5644),
                            Status = 1,
                            Value = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.ProductAttribute", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ProductAttributes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AttributeName = "Rubber",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5143),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            AttributeName = "Granite",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5179),
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            AttributeName = "Frozen",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5202),
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            AttributeName = "Steel",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5224),
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            AttributeName = "Rubber",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5247),
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            AttributeName = "Granite",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5270),
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            AttributeName = "Wooden",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5292),
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            AttributeName = "Frozen",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5314),
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            AttributeName = "Steel",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5336),
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            AttributeName = "Plastic",
                            CreatedDate = new DateTime(2024, 6, 4, 16, 9, 10, 680, DateTimeKind.Local).AddTicks(5358),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Shipper", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserProfile", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithOne("Profile")
                        .HasForeignKey("Project.ENTITIES.Models.AppUserProfile", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserID");

                    b.HasOne("Project.ENTITIES.Models.Shipper", "Shipper")
                        .WithMany("Orders")
                        .HasForeignKey("ShipperID");

                    b.Navigation("AppUser");

                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.ProductAndProductAttribute", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.ProductAttribute", "ProductAttribute")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductAttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Product", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductAttribute");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.ProductAttribute", b =>
                {
                    b.Navigation("ProductAttributes");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Shipper", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
