// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.ContextClasses;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240604202555_mtn3")]
    partial class mtn3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "710c05a3-1990-448d-a86f-b31fcc1102e7",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(4215),
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d097b2a4-89a2-4a1e-a2fa-968793eb04b1",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(4447),
                            Email = "metinmustafaaltintas@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "METINMUSTAFAALTINTAS@GMAIL.COM",
                            NormalizedUserName = "METIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEE3czHFswzi9O2XddQOtmAvvXxJPAyDyOG7s41zt3IZ2pqU3BD+zrGvPQDMdb7Bcqg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6124cb3c-14a9-4fc5-930b-2319375d7693",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "metin"
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserProfile", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 534, DateTimeKind.Local).AddTicks(8105),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Automotive",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(1173),
                            Description = "Quae fugit quia adipisci eum consequatur açılmadan lakin ullam sed.",
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Shoes",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(1657),
                            Description = "Eos kutusu tempora sunt non gitti quam quaerat mi deleniti.",
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Shoes",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(1746),
                            Description = "Olduğu dergi sevindi ratione sevindi eius non voluptatem bundan et.",
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Tools",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(1820),
                            Description = "Consequatur voluptate mi alias makinesi masanın türemiş tempora totam ama.",
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Music",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(1907),
                            Description = "İusto sequi quaerat gitti kutusu aliquam oldular sıfat consectetur aliquid.",
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Outdoors",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(1983),
                            Description = "Voluptas filmini sıla in ea adanaya kulu voluptatem ipsa lakin.",
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Outdoors",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(2054),
                            Description = "Tempora nemo consequatur reprehenderit corporis şafak masanın için qui exercitationem.",
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Movies",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(2123),
                            Description = "Adanaya esse yapacakmış gül doloremque quam et nemo magni olduğu.",
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Health",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(2201),
                            Description = "Umut sit quia yaptı quia masanın sit sed koyun velit.",
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Kids",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(2271),
                            Description = "Ea otobüs velit eos aliquid enim laboriosam koşuyorlar otobüs dolor.",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceOfOrder")
                        .HasColumnType("money");

                    b.Property<int?>("ShipperID")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AppUserID");

                    b.HasIndex("ShipperID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(2426),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Intelligent Cotton Keyboard",
                            Status = 1,
                            UnitPrice = 611.85m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(2846),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Ergonomic Steel Computer",
                            Status = 1,
                            UnitPrice = 28.64m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(2955),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Unbranded Metal Car",
                            Status = 1,
                            UnitPrice = 510.43m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3043),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Ergonomic Cotton Keyboard",
                            Status = 1,
                            UnitPrice = 353.12m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3123),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Gorgeous Granite Bacon",
                            Status = 1,
                            UnitPrice = 23.38m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 6,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3204),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Handmade Wooden Computer",
                            Status = 1,
                            UnitPrice = 95.08m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 7,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3294),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Intelligent Rubber Chair",
                            Status = 1,
                            UnitPrice = 259.87m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 8,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3375),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Fantastic Fresh Shoes",
                            Status = 1,
                            UnitPrice = 224.60m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 9,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3455),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Awesome Metal Table",
                            Status = 1,
                            UnitPrice = 746.32m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 10,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3539),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Generic Fresh Shirt",
                            Status = 1,
                            UnitPrice = 776.43m,
                            UnitsInStock = 100
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.ProductAndProductAttribute", b =>
                {
                    b.Property<int>("ProductAttributeID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductAttributeID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductAndProductAttributes");

                    b.HasData(
                        new
                        {
                            ProductAttributeID = 1,
                            ProductID = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3959),
                            Status = 1,
                            Value = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J"
                        },
                        new
                        {
                            ProductAttributeID = 2,
                            ProductID = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3990),
                            Status = 1,
                            Value = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            ProductAttributeID = 3,
                            ProductID = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(4012),
                            Status = 1,
                            Value = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            ProductAttributeID = 4,
                            ProductID = 4,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(4031),
                            Status = 1,
                            Value = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            ProductAttributeID = 5,
                            ProductID = 5,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(4057),
                            Status = 1,
                            Value = "The Football Is Good For Training And Recreational Purposes"
                        },
                        new
                        {
                            ProductAttributeID = 6,
                            ProductID = 6,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(4078),
                            Status = 1,
                            Value = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            ProductAttributeID = 7,
                            ProductID = 7,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(4097),
                            Status = 1,
                            Value = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            ProductAttributeID = 8,
                            ProductID = 8,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(4116),
                            Status = 1,
                            Value = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            ProductAttributeID = 9,
                            ProductID = 9,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(4135),
                            Status = 1,
                            Value = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            ProductAttributeID = 10,
                            ProductID = 10,
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(4155),
                            Status = 1,
                            Value = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.ProductAttribute", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ProductAttributes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AttributeName = "Fresh",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3688),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            AttributeName = "Fresh",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3732),
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            AttributeName = "Granite",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3754),
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            AttributeName = "Steel",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3774),
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            AttributeName = "Granite",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3795),
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            AttributeName = "Soft",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3816),
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            AttributeName = "Steel",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3836),
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            AttributeName = "Metal",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3856),
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            AttributeName = "Wooden",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3875),
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            AttributeName = "Steel",
                            CreatedDate = new DateTime(2024, 6, 4, 23, 25, 54, 431, DateTimeKind.Local).AddTicks(3896),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Shipper", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserProfile", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithOne("Profile")
                        .HasForeignKey("Project.ENTITIES.Models.AppUserProfile", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserID");

                    b.HasOne("Project.ENTITIES.Models.Shipper", "Shipper")
                        .WithMany("Orders")
                        .HasForeignKey("ShipperID");

                    b.Navigation("AppUser");

                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.ProductAndProductAttribute", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.ProductAttribute", "ProductAttribute")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductAttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Product", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductAttribute");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.ProductAttribute", b =>
                {
                    b.Navigation("ProductAttributes");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Shipper", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
