// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.ContextClasses;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240604121432_mtn1")]
    partial class mtn1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "19506cf5-2c5d-45fa-87ee-3886a93c86e0",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(6413),
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "13ea3109-7428-4c12-a41f-6b0024a58928",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(7077),
                            Email = "metinmustafaaltintas@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "METINMUSTAFAALTINTAS@GMAIL.COM",
                            NormalizedUserName = "METIN",
                            PasswordHash = "AQAAAAIAAYagAAAAELIyq7oUVuFBhO6m+OtOoS7P1DGZWeRI7oxEAVDygdpUoKKwobPCDoXZL0hJAVfXwg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "56c4875c-2767-44f7-ac4f-04b8bd6f2a26",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "metin"
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserProfile", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ctiy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 519, DateTimeKind.Local).AddTicks(684),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Garden",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(1595),
                            Description = "Sit ki veritatis quis incidunt yaptı quis teldeki tv bundan.",
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Clothing",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(2239),
                            Description = "Exercitationem velit orta dicta perferendis inventore yapacakmış ex yapacakmış cesurca.",
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Toys",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(2353),
                            Description = "İnventore quia çünkü ut exercitationem sıradanlıktan dicta bahar nisi alias.",
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Automotive",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(2424),
                            Description = "Çünkü ut otobüs enim sıradanlıktan sit odit sevindi quia suscipit.",
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Grocery",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(2500),
                            Description = "Adanaya patlıcan reprehenderit çorba adresini corporis bilgisayarı mi bahar makinesi.",
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Grocery",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(2577),
                            Description = "Aperiam nisi camisi sandalye cesurca sıla ut kutusu quia incidunt.",
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Outdoors",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(2859),
                            Description = "Ama consequatur sevindi sandalye totam un ona lakin türemiş aut.",
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Outdoors",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(2936),
                            Description = "Layıkıyla nemo consequuntur umut patlıcan aut ut nesciunt dolor şafak.",
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Kids",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(3194),
                            Description = "Eve lakin minima iusto değerli illo sed sed gitti gül.",
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Music",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(3632),
                            Description = "Açılmadan sayfası çobanın sevindi voluptatem vel rem esse çıktılar blanditiis.",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceOfOrder")
                        .HasColumnType("money");

                    b.Property<int?>("ShipperID")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AppUserID");

                    b.HasIndex("ShipperID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(3883),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Sleek Fresh Salad",
                            Status = 1,
                            UnitPrice = 350.05m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(4231),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Practical Frozen Computer",
                            Status = 1,
                            UnitPrice = 34.71m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(4331),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Unbranded Wooden Towels",
                            Status = 1,
                            UnitPrice = 117.65m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(4417),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Handmade Rubber Car",
                            Status = 1,
                            UnitPrice = 755.16m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(4688),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Tasty Concrete Car",
                            Status = 1,
                            UnitPrice = 186.67m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 6,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(4974),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Generic Wooden Pants",
                            Status = 1,
                            UnitPrice = 58.40m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 7,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5057),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Gorgeous Rubber Cheese",
                            Status = 1,
                            UnitPrice = 684.12m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 8,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5138),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Tasty Plastic Chips",
                            Status = 1,
                            UnitPrice = 436.03m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 9,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5220),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Sleek Metal Keyboard",
                            Status = 1,
                            UnitPrice = 96.38m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 10,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5313),
                            ImagePath = "http://lorempixel.com/640/480/nightlife",
                            ProductName = "Awesome Soft Soap",
                            Status = 1,
                            UnitPrice = 946.23m,
                            UnitsInStock = 100
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.ProductAndProductAttribute", b =>
                {
                    b.Property<int>("ProductAttributeID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductAttributeID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductAndProductAttributes");

                    b.HasData(
                        new
                        {
                            ProductAttributeID = 1,
                            ProductID = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(6149),
                            Status = 1,
                            Value = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            ProductAttributeID = 2,
                            ProductID = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(6180),
                            Status = 1,
                            Value = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J"
                        },
                        new
                        {
                            ProductAttributeID = 3,
                            ProductID = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(6203),
                            Status = 1,
                            Value = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            ProductAttributeID = 4,
                            ProductID = 4,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(6223),
                            Status = 1,
                            Value = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support"
                        },
                        new
                        {
                            ProductAttributeID = 5,
                            ProductID = 5,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(6243),
                            Status = 1,
                            Value = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            ProductAttributeID = 6,
                            ProductID = 6,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(6265),
                            Status = 1,
                            Value = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart"
                        },
                        new
                        {
                            ProductAttributeID = 7,
                            ProductID = 7,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(6285),
                            Status = 1,
                            Value = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            ProductAttributeID = 8,
                            ProductID = 8,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(6304),
                            Status = 1,
                            Value = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            ProductAttributeID = 9,
                            ProductID = 9,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(6323),
                            Status = 1,
                            Value = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            ProductAttributeID = 10,
                            ProductID = 10,
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(6343),
                            Status = 1,
                            Value = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support"
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.ProductAttribute", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ProductAttributes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AttributeName = "Wooden",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5471),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            AttributeName = "Rubber",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5718),
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            AttributeName = "Fresh",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5741),
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            AttributeName = "Steel",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5763),
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            AttributeName = "Granite",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5783),
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            AttributeName = "Soft",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5805),
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            AttributeName = "Rubber",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5826),
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            AttributeName = "Rubber",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5846),
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            AttributeName = "Frozen",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5866),
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            AttributeName = "Concrete",
                            CreatedDate = new DateTime(2024, 6, 4, 15, 14, 31, 421, DateTimeKind.Local).AddTicks(5896),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Shipper", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserProfile", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithOne("Profile")
                        .HasForeignKey("Project.ENTITIES.Models.AppUserProfile", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserRole", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserID");

                    b.HasOne("Project.ENTITIES.Models.Shipper", "Shipper")
                        .WithMany("Orders")
                        .HasForeignKey("ShipperID");

                    b.Navigation("AppUser");

                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.OrderDetail", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.ProductAndProductAttribute", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.ProductAttribute", "ProductAttribute")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductAttributeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Product", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductAttribute");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Product", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.ProductAttribute", b =>
                {
                    b.Navigation("ProductAttributes");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Shipper", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
